### ISSUE TITLE
Replace ast.NameConstant with ast.Constant

### ISSUE THREAD

**Issue by andreinaku** [coetaur0/staticfg#14]
Hello!

**ast.NameConstant** has been deprecated in Python 3.8 and **ast.Constant** is used for all constants. This might affect *builder.py::invert* and *builder.py::visit_While*.

**Comment by andreinaku** [comment]
I created a pull request that might help with this issue + some other fun stuff here: https://github.com/coetaur0/staticfg/pull/15

**Comment by leonardt** [comment]
Should be fixed by #15 (sorry had a NameError in my last change which is fixed on master)
