### ISSUE TITLE
handling attributes in ast.Call

### ISSUE THREAD

**Issue by ravi-ilango** [coetaur0/staticfg#16]
Hi,

I would like to add the following code to handle parsing of attributes and function names.  The current code does not handle constructs such as    "-".join(somelist)

Thanks!

    def visit_Call(self, node):
        def visit_func(node):
            if type(node) == ast.Name:
                return node.id

           # start changes
            elif type(node) == ast.Attribute:
                # Recursion on series of calls to attributes.
                if type(node.value) == ast.Call:
                    func_name = visit_func(node.value.func)
                elif type(node.value) == ast.Constant:
                    func_name = node.value.value
                else:
                    func_name = visit_func(node.value)
           # end changes

                func_name += "." + node.attr
                return func_name
            elif type(node) == ast.Str:
                return node.s
            elif type(node) == ast.Subscript:
                return node.value.id

**Comment by coetaur0** [comment]
Fixed in [ef31729](https://github.com/coetaur0/staticfg/commit/ef3172950f459394101fc2cb311d36a2f6eebf6b).
