### ISSUE TITLE
Using other modules

### ISSUE THREAD

**Issue by jeshan** [coetaur0/staticfg#7]
staticfg is looking great for single-file sources. Are there any plans to draw the call graphs with imported modules? What would be needed to make this happen?

**Comment by coetaur0** [comment]
Hi, sorry for the late reply. Unfortunately, I don't have any time currently to implement this. I'd need to investigate the question a little more to be sure of how to do this, but I think you'd probably need to make some changes in the `visit_Import()` method of the `CFGBuilder` class to make it possible.
